version: 2.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: x64
before_build:
- cmd: nuget restore
build:
  project: SSH_KEY_GENERATER.sln
  verbosity: minimal
artifacts:
- path: SSH_KEY_GENERATER\bin\Release
  name: ssh_key_generater_stable
deploy:
- provider: GitHub
  tag: SSH_KEY_GENERATER-v$(appveyor_build_version)
  release: SSH_KEY_GENERATER-v$(appveyor_build_version)
  auth_token:
    secure: C6qp4NUrPAueR6AAoNUkFivJvn9kJ3xACtbUumYqUllBXlmVxNZBeWuwO1eU0bnO
